defaults:
  actions:
    queue:
      allow_merging_configuration_change: true

queue_rules:
  - name: default
    conditions:
      - check-success=buildbot/nix-eval

pull_request_rules:
  - name: Automerge PRs using the merge queue
    conditions:
      - "label=merge-queue"
      - "base=main"
    actions:
      queue:
        name: default
        method: squash

  - name: Delete head branch after merge
    conditions:
      - "merged"
    actions:
      delete_head_branch: {}
